module GistsHelper
  def pyments_languages
    [
      "ActionScript",
      "Ada",
      "ANTLR",
      "AppleScript",
      "Assembly",
      "Asymptote",
      "Awk",
      "Befunge",
      "Boo",
      "BrainFuck",
      "C",
      "C++",
      "C#",
      "Clojure",
      "CoffeeScript",
      "ColdFusion",
      "Common Lisp",
      "Coq",
      "Cython",
      "D",
      "Dart",
      "Delphi",
      "Dylan",
      "Erlang",
      "Factor",
      "Fancy",
      "Fortran",
      "F#",
      "Cucumber",
      "GL shaders",
      "Groovy",
      "Haskell",
      "IDL",
      "Io",
      "Java",
      "JavaScript",
      "LLVM",
      "Logtalk",
      "Lua",
      "Matlab",
      "MiniD",
      "Modelica",
      "Modula-2",
      "MuPad",
      "Nemerle",
      "Nimrod",
      "Objective-C",
      "Objective-J",
      "Octave",
      "OCaml",
      "PHP",
      "Perl",
      "PovRay",
      "PostScript",
      "PowerShell",
      "Prolog",
      "Python",
      "Rebol",
      "Redcode",
      "Ruby",
      "Rust",
      "S",
      "S-Plus",
      "R",
      "Scala",
      "Scheme",
      "Scilab",
      "Smalltalk",
      "SNOBOL",
      "Tcl",
      "Vala",
      "Verilog",
      "VHDL",
      "Visual Basic.NET",
      "Visual FoxPro",
      "XQuery",
      "Cheetah",
      "Django",
      "Jinja",
      "ERB",
      "Genshi",
      "JSP",
      "Myghty",
      "Mako",
      "Smarty Template",
      "Tea",
      "Apache Config",
      "Bashshell",
      "BBCode",
      "CMake",
      "CSS",
      "Debian control files",
      "Diff files",
      "DTD",
      "Gettext catalogs",
      "Gnuplot script",
      "Groff markup",
      "HTML",
      "HTTP Session",
      "INI-style config files",
      "IRC logs (irssi style)",
      "Lighttpd config files",
      "Makefiles",
      "MoinMoin/Trac Wiki markup",
      "MySQL",
      "Nginx Config",
      "POV-Ray scenes",
      "Ragel",
      "Redcode",
      "ReST",
      "Robot Framework",
      "RPM Spec",
      "SQL",
      "Squid",
      "TeX",
      "tcsh",
      "Vim Script",
      "Batchfile",
      "XML",
      "XSLT",
      "YAML"
    ]
  end
end
